const config = {
    darkMode: "class",
    content: [
        "./app/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "on-secondary-fixed-variant": "#3b475b",
                "surface-container-lowest": "#ffffff",
                "on-surface": "#051a3e",
                "inverse-surface": "#1d3054",
                "on-tertiary": "#ffffff",
                "on-surface-variant": "#434654",
                "tertiary-fixed": "#d7e2ff",
                outline: "#737685",
                "on-tertiary-container": "#bfd3ff",
                "on-primary-fixed-variant": "#0040a2",
                "surface-container": "#e9edff",
                error: "#ba1a1a",
                "surface-tint": "#0c56d0",
                "on-primary-fixed": "#001848",
                "secondary-container": "#d4e0f8",
                "on-secondary": "#ffffff",
                "surface-container-highest": "#d8e2ff",
                "on-secondary-fixed": "#101c2d",
                primary: "#003d9b",
                "surface-variant": "#d8e2ff",
                "tertiary-container": "#0058b6",
                "surface-container-low": "#f1f3ff",
                "on-tertiary-fixed-variant": "#004590",
                secondary: "#535f73",
                surface: "#faf9ff",
                "surface-container-high": "#e1e8ff",
                "surface-bright": "#faf9ff",
                "outline-variant": "#c3c6d6",
                "secondary-fixed": "#d7e3fb",
                "on-background": "#051a3e",
                background: "#faf9ff",
                "on-primary-container": "#c4d2ff",
                "primary-container": "#0052cc",
                "primary-fixed": "#dae2ff",
                "tertiary-fixed-dim": "#abc7ff",
                "on-tertiary-fixed": "#001b3f",
                "on-primary": "#ffffff",
                "secondary-fixed-dim": "#bbc7de",
                tertiary: "#00418a",
                "primary-fixed-dim": "#b2c5ff",
                "surface-dim": "#ccdaff",
                "inverse-on-surface": "#edf0ff",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                "on-secondary-container": "#576377",
                "inverse-primary": "#b2c5ff",
                "on-error": "#ffffff",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                xxl: "48px",
                lg: "24px",
                unit: "4px",
                gutter: "24px",
                xl: "32px",
                md: "16px",
                xs: "4px",
                margin: "32px",
                sm: "8px",
            },
            fontFamily: {
                "headline-sm": ["Inter"],
                "label-md": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "headline-md": ["Inter"],
                caption: ["Inter"],
                "headline-lg": ["Inter"],
                "body-lg": ["Inter"],
                "label-sm": ["Inter"],
                "body-md": ["Inter"],
            },
            fontSize: {
                "headline-sm": [
                    "20px",
                    { lineHeight: "28px", fontWeight: "600" },
                ],
                "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
                "headline-lg-mobile": [
                    "24px",
                    {
                        lineHeight: "32px",
                        letterSpacing: "-0.01em",
                        fontWeight: "700",
                    },
                ],
                "headline-md": [
                    "24px",
                    {
                        lineHeight: "32px",
                        letterSpacing: "-0.01em",
                        fontWeight: "600",
                    },
                ],
                caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
                "headline-lg": [
                    "32px",
                    {
                        lineHeight: "40px",
                        letterSpacing: "-0.02em",
                        fontWeight: "700",
                    },
                ],
                "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "label-sm": [
                    "12px",
                    {
                        lineHeight: "16px",
                        letterSpacing: "0.02em",
                        fontWeight: "600",
                    },
                ],
                "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
            },
        },
    },
    plugins: [],
};
export default config;
